services:
  - docker:dind

default:
  image: docker:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_docker:
  stage: build
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:lates .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  only:
    - tags
    - /v\d+\.\d+\.\d+/
    - triggers
    - schedules

build_master_docker:
  stage: build
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:master .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:master
  only:
    - master
    - triggers

build_tagged_docker:
  stage: build
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG} .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}
  only:
    - tags
    - triggers

stages:
  - build
