default:
  image: docker.registry.org.il/imageroot/buildah:latest

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/openlaw-bot/${CI_COMMIT_TAG}/"

stages:
  - build
  - release
  - deploy

.container:
  before_script:
    - echo $CI_REGISTRY_PASSWORD | buildah login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

build-master-container:
  extends: .container
  stage: build
  script:
    - buildah build -t ${CI_REGISTRY_IMAGE}:master .
    - buildah push ${CI_REGISTRY_IMAGE}:master
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

build-tagged-container:
  extends: .container
  stage: build
  script:
    - buildah build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} -t ${CI_REGISTRY_IMAGE}:latest .
    - buildah push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - buildah push ${CI_REGISTRY_IMAGE}:latest
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'

build-tagged-artifact:
  stage: build
  image: alpine:latest
  before_script:
   - apk add curl
  script:
    - tar czf openlaw-bot.tar.gz README.md LICENSE *.pl *.pm
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file openlaw-bot.tar.gz "${PACKAGE_REGISTRY_URL}/openlaw-bot.tar.gz"'
  artifacts:
    paths:
      - openlaw-bot.tar.gz
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  variables:
    GIT_STRATEGY: none
  needs:
    - build-tagged-container
    - build-tagged-artifact
  script:
    - echo 'Releasing code'
  release:
    name: 'OpenLaw Bot ${CI_COMMIT_TAG}'
    description: 'Released version ${CI_COMMIT_TAG}'
    tag_name: '${CI_COMMIT_TAG}'
    ref: '${CI_COMMIT_TAG}'
    assets:
      links:
        - name: openlaw-bot.tar.gz
          filepath: /openlaw-bot.tar.gz
          url: "${PACKAGE_REGISTRY_URL}/openlaw-bot.tar.gz"
          link_type: package
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'

deploy:
  stage: deploy
  needs:
    - release
  variables:
    ANSIBLE_TAGS: openlaw-bot
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'
  trigger:
    project: resource-il/openlaw-infra
    branch: master
    strategy: depend

fetch-downstream-info:
  stage: deploy
  needs:
    - release
  image: alpine:latest
  variables:
    GIT_STRATEGY: none
  script:
    - apk add -q curl jq
    - OPENLAW_TOOLS_TAG_LATEST=$(curl "${CI_API_V4_URL}/projects/resource-il%2Fopenlaw-tools/releases?per_page=1" | jq -r '.[].ref')
    - echo "OPENLAW_TOOLS_TAG_LATEST=${OPENLAW_TOOLS_TAG_LATEST}" | tee versions.env
  artifacts:
    reports:
      dotenv: versions.env
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'

update-tools:
  stage: .post
  needs:
    - job: fetch-downstream-info
      artifacts: true
  variables:
    OPENLAW_BOT_VERSION: ${CI_COMMIT_TAG}
  trigger:
    project: resource-il/openlaw-tools
    branch: ${OPENLAW_TOOLS_TAG_LATEST}
    strategy: depend
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'
