services:
  - docker:dind

default:
  image: docker:latest

before_script:
  - docker info
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

build_latest_docker:
  stage: build
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
    - /v\d+\.\d+\.\d+/
  except:
    - branches

build_master_docker:
  stage: build
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:master .
    - docker push ${CI_REGISTRY_IMAGE}:master
  only:
    - master
  except:
    - tags

build_tagged_docker:
  stage: publish
  script:
    - docker pull ${CI_REGISTRY_IMAGE}:latest
    - docker tag ${CI_REGISTRY_IMAGE}:latest ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  only:
    - tags
  except:
    - branches
    - schedules
    - triggers
  dependencies:
    - build_latest_docker

stages:
  - build
  - publish
