image: docker:latest

services:
  - docker:dind

stages:
  - build
  - release
  - deploy

.docker:
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

build_master_docker:
  extends: .docker
  stage: build
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:master .
    - docker push ${CI_REGISTRY_IMAGE}:master
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

build_tagged_docker:
  extends: .docker
  stage: build
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} .
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - docker push ${CI_REGISTRY_IMAGE}:latest
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - build_tagged_docker
  script:
    - echo 'Releasing code'
  release:
    name: 'OpenLaw Bot ${CI_COMMIT_TAG}'
    description: 'Released version ${CI_COMMIT_TAG}'
    tag_name: '${CI_COMMIT_TAG}'
    ref: '${CI_COMMIT_TAG}'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'

deploy:
  stage: deploy
  needs:
    - release
  variables:
    ANSIBLE_TAGS: openlaw-bot
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'
  trigger:
    project: resource-il/openlaw-infra
    branch: master
    strategy: depend
